name: 'Check for merge conflicts'
on:
  pull_request:
    branches:
      - master
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label merge conflicts
        uses: mschilde/auto-label-merge-conflicts@v2.0
        with: 
            CONFLICT_LABEL_NAME: "has conflicts"
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
