name: Pull Request in master
on: 
  pull_request_target:
    branches:
      - master // destination branch where this workflow will trigger

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
