name: 'Base_Branch_Master_Selected_Label'
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master   
jobs:
  Job1:    
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v2
      - uses: mschilde/auto-label-merge-conflicts@master
        with:          
          CONFLICT_LABEL_NAME: 'selected master'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
