name: Pull Request in master
on: 
  pull_request:
    branches:
      - master // destination branch where this workflow will trigger
      - main
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Labeler
      uses: actions/labeler@v3
      with:
        CONFLICT_LABEL_NAME: 'selected master'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
