name: 'Check for master'
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  triage:
    runs-on: ubuntu-latest    
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:          
            CONFLICT_LABEL_NAME: 'selected master'
            repo-token: "${{ secrets.GITHUB_TOKEN }}"       
