name: 'Check for merge conflicts'
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'   
jobs:
  triage:
    runs-on: ubuntu-latest    
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          if: github.event.pull_request.base.ref == 'master'           
          CONFLICT_LABEL_NAME: 'selected master'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
