name: 'Check for merge conflicts'
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'   
jobs:
  Job1:
    name: Base_Branch_Master_Selected_Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          if: ${{ github.base_sha == 'master' }}
#           if: github.event.pull_request.base.sha == 'master'
          CONFLICT_LABEL_NAME: 'selected master'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Job2:
    name: Merge_Conflict_label
    runs-on: ubuntu-latest    
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: 'has conflicts'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Job3:  
    name: Check that PR has description
    runs-on: ubuntu-latest

    steps:
        - name: Check if PR is shame-worthy
          id: is-shame-worthy
          run: |
              FILTERED_BODY=$( sed -r -e '/^(##? )|(- *\[)/d' <<< $RAW_BODY )
              echo "::debug::Filtered PR body to $FILTERED_BODY"
              if [[ -z "${FILTERED_BODY//[[:space:]]/}" ]]; then
                  echo "::set-output name=is-shame-worthy::true"
              else
                  echo "::set-output name=is-shame-worthy::false"
              fi
          env:
              RAW_BODY: ${{ github.event.pull_request.body }}

        - name: Shame if PR has no description
          if: steps.is-shame-worthy.outputs.is-shame-worthy == 'true'
          run: |
              SHAME_BODY="Hey @${{ github.actor }}! 👋\nThis pull request seems to contain no description. Please add useful context, rationale, and/or any other information that will help make sense of this change now and in the distant Mars-based future."
              curl -s -u posthog-bot:${{ secrets.GITHUB_TOKEN }} -X POST -d "{ \"body\": \"$SHAME_BODY\" }" "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
          
