name: 'Check for merge conflicts'
on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'   
jobs:
  triage:
    runs-on: ubuntu-latest    
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: 'selected master'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
