name: 'Check for merge conflicts'
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'   
jobs:
  Job1:
    name: Base_Branch_Master_Selected_Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          if: ${{ github.base_sha == 'master' }}
#           if: github.event.pull_request.base.sha == 'master'
          CONFLICT_LABEL_NAME: 'selected master'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Job2:
    name: Merge_Conflict_label
    runs-on: ubuntu-latest    
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: 'has conflicts'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Job3:
    name: Current Branch
    runs-on: ubuntu-latest
    steps:
      - name: Current Branch
      # You may pin to the exact commit or the version.
      # uses: ryolambert/current-branch@e8b56c41a563d56e7e73d369f2ed742a6f37bf97
        uses: ryolambert/current-branch@v1.0

