name: 'Check for master'
on: 
  pull_request:
    branches:
      - master
      - develop
jobs:
  triage:
    runs-on: ubuntu-latest    
    steps:
      - uses: abc/abc@master
        with:
            CONFLICT_LABEL_NAME: 'selected master'
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
      
    
      
        
