name: 'Pull request in Master'
on:  
  pull_request:
    branches:
      - master
      - main
jobs:
  triage:
    runs-on: ubuntu-latest    
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: 'selected master'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
