name: 'Check for master'
on: 
  pull_request:
    branches:
      - master
      - develop
jobs:
  triage:
    if: ${{ github.event.pull_request.base.ref == 'master' }}
    runs-on: ubuntu-latest    
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: 'selected master'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
      
    
      
        
